name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Proposal
      description: What problem does it solve?
    validations: { required: true }
